FROM node:18-alpine

WORKDIR /app/frontend

# Copy package files
COPY app/frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY app/frontend .

# Expose the port the app runs on
EXPOSE 5173

# Command to run the application
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
